import { readFileSync } from 'node:fs';
const html=readFileSync(new URL('../index.html',import.meta.url),'utf8');
const css=readFileSync(new URL('../styles.css',import.meta.url),'utf8');
const js=readFileSync(new URL('../app.js',import.meta.url),'utf8');
const sw=readFileSync(new URL('../sw.js',import.meta.url),'utf8');
const must=(text,part,label)=>{if(!text.includes(part))throw new Error(`missing ${label}`)};
['小于的考研课表','id="daily-agenda"','id="phase-line"','id="syllabus-table"','id="major-method"','id="app-version"','13天全天冲刺','9月12日至24日','9月11日任务未完成','00:00关灯','styles.css?v=sprint-0912d','app.js?v=sprint-0912d',"serviceWorker.register('sw.js?v=sprint-0912d')"].forEach(x=>must(html,x,x));
['kaoyan-sprint-0912d',"addEventListener('fetch'",'caches.delete','skipWaiting'].forEach(x=>must(sw,x,x));
['intensiveSprintStart','intensiveSprintEnd','intensiveSprintAgenda','intensiveSprintActive','2026-09-12','2026-09-24','9/11没有完成任何计划任务','第4、5、6个都未确认完成','先补9月10日剩余15题','P=前置未学','00:00关灯','majorSecondDayCompletedUnits = 0',"const APP_VERSION = 'sprint-0912d'"].forEach(x=>must(js,x,x));
if(js.includes('9月11日20:16实际只确认第4个'))throw new Error('obsolete 9/11 completion claim remains in the live route');
['@media(max-width:900px)','agenda-item','brush-focus','touch-action:pan-y'].forEach(x=>must(css,x,x));
console.log('SMOKE_STATIC_OK sprint-0912d');